---
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-prod
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (all interfaces)
    # Note: Using 0.0.0.0 exposes the API to all network interfaces
    # Please ensure proper security measures are in place
    ports:
      - "0.0.0.0:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3-prod.sqlite
      --config /freqtrade/user_data/config-prod.json
      --config /freqtrade/user_data/config-private.json
      --strategy NFI5MOHO_WIP
